services:
  stock-predictor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-predictor
    ports:
      - "8000:8000"
    volumes:
      - ./inference:/app/inference
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    networks:
      - auth
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  news-analyzer:
    build:
      context: ./news-analyzer
      dockerfile: Dockerfile
    container_name: news-analyzer
    ports:
      - "8092:8092"
    volumes:
      - ./news-analyzer:/app
      - ./logs:/app/logs
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - PORT=8092
      - HOST=0.0.0.0
    networks:
      - auth
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8092/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
      
networks:
  auth:
    external: true
