services:
  stock-predictor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-predictor
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - stockai-backend_auth
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  news-analyzer:
    build:
      context: ./news-analyzer
      dockerfile: Dockerfile
    container_name: news-analyzer
    ports:
      - "8001:8001"
    volumes:
      - ./news-analyzer:/app
      - ./logs:/app/logs
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - stockai-backend_auth
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
      
networks:
  stockai-backend_auth:
    external: true
